const { EmbedBuilder } = require("discord.js");

module.exports = {
  name: "truth",
  description: "Give a random truth",
  category: "Fun",
  aliases: ["truth"],
  cooldown: 3,
  args: false,
  usage: "",
  userPerms: [],
  owner: false,
  execute(message, args, client, prefix) {
    const truth = [
      "When was the last time you told a lie?",
      "What is your biggest fear?",
      "What is your guilty pleasure?",
      "Who do you have a crush on?",
      "If you had to date someone in this room who would it be?",
      "Have you ever been cheated on someone?",
      "Have you ever been cheated on?",
      "What is the meanest thing that you have done?",
      "What was your first kiss like?",
      "Who is the last person that you stalked on social media?",
      "What is the craziest event that you have ever been to?",
      "When was the last time you peed yourself?",
      "What is the worst dream that you have had?",
      "Why did your last relationship end?",
      "What is the most embarrassing thing that has happened to you this year?",
      "What habit can’t you seem to quit?",
      "Who is your celebrity crush?",
      "What is your least favorite thing about your best friend?",
      "What don’t you like about your boyfriend or girlfriend?",
      "Have you ever hooked up with the same sex?",
      "What is a secret that you have never told anyone before?",
      "How many people have you kissed?",
      "How many people have you been with?",
      "Has anyone ever accidentally seen you naked? Who?",
      "Have you ever gone out without wearing a bra and underwear?",
      "Who is your crush in this server?",
      "Who was your first love?",
      "What is your biggest regret?",
      "Would you stop talking to all of your friends for a million dollars?",
      "Have you ever committed a crime? If so what was it?",
      "Have you ever been to jail?",
      "Who was your first crush?",
      "Would you ever cheat on your significant other if they said it was okay?",
      "Would you ever be polygamous?",
      "Have you ever had a crush on your teacher/professor?",
      "Have you ever had a crush on your best friend’s mom or someone generally much older that you?",
      "If you were the opposite gender for the day? What do you think you would wear? What would you do?",
      "What is the most embarrassing music that you like to listen to?",
      "If you and one person in this room could be the last people on Earth left alive who would that person be?",
      "Would you ever donate an organ to someone in this room?",
      "Who in this room do you think would be the worst date?",
      "Who in this room do you think would be the best date?",
      "What is your secret talent if you have one?",
      "What is the worst intimate experience that you have had?",
      "What is the worst thing about being your gender?",
      "If you were a superhero what would your power be?",
      "Have you ever performed a striptease for anyone before?",
      "Have you ever eaten food from the floor?",
      "Have you ever cheated on an exam?",
      "Have you ever been suspended from school?",
      "What is the most trouble that you ever got into in school?",
      "What is the most trouble that you ever got into at home / with your parents?",
      "When was a time that someone really betrayed your trust?",
      "Talk about a time that you failed in life.",
      "Tell us about a time that you were really drunk.",
      "Have you ever spread a rumor?",
      "Have you ever been intimate in a public place?",
      "What is something you used to do that makes you cringe now?",
      "Do you sing in the shower?",
      "When is the last time you threw up?",
      "When is the last time you cried?",
      "Have you ever laughed so hard that you cried?",
      "Have you ever cried from watching a TV show or a movie?",
      "What is the most embarrassing thing that you have ever done in front of a crush?",
      "What do you look for in a potential love interest?",
      "Would you rather be rich or famous? You cannot be both.",
      "What would you do with a million dollars?",
      "Could you survive without any phone or internet for a month?",
      "What is the most that you have ever had to drink?",
      "What is the longest amount of time that you have ever been awake?",
      "If you could do it what would you change your name to?",
      "Name a famous person that you would like to be friends with.",
      "Who are 5 famous people that you would like to have dinner with? They can either be dead or alive.",
      "What is your biggest pet peeve?",
      "When was the worst time that you threw up?",
      "If you could only save one person in this room from a fire who would it be?",
      "Who is the most attractive person in the room?",
      "Who is the most annoying person in the room?",
      "Which person in the room do you think gossips the most?",
      "What is your biggest insecurity?",
      "What is the most expensive thing you bought that wasn’t a house or a car?",
      "What is a common misconception about you?",
      "What is something that you would do that people would assume you would never do?",
      "Where is the weirdest place that you have gone to the bathroom?",
      "What is the most embarrassing thing that your parents have caught you doing?",
      "When was the most embarrassing time that you passed gas?",
      "What was the most disgusting thing to ever come out of your body?",
      "What is the most disgusting thing that you have ever had in your mouth?",
      "How old do you think you will live to be?",
      "What do you want to do when you are retired?",
      "If you could live anywhere in the world where would it be?",
      "What do you think is your best physical quality?",
      "Have you ever had a run-in with the law?",
      "What can you sometimes be prejudiced about?",
      "When is the last time you talked about someone behind their back?",
      "Who is your least favorite friend?",
      "Would you kiss the person on your left?",
      "Who is the sexiest person in the room?",
      "Do you shower every day?",
      "Do you brush teeth every day?",
      "Do you floss your teeth every day?",
      "Have you ever gotten a DUI?",
      "What would you do if you could retire at 40?",
      "Have you ever been tempted to cheat on someone?",
      "Have you ever had a one night stand?",
      "Would you ever get a tattoo? What kind of tattoo would it be?",
      "What is your least favorite thing about your best friend?",
      "Have you ever wanted to kill someone?",
      "Have you ever gotten into a physical altercation with anyone?",
      "If you could only eat one food every day for the rest of your life what would it be?",
      "Have you ever had feelings for a friend or family member’s significant other?",
      "What is the worst thing that anyone has ever said about you?",
      "What is the worst thing that somebody ever said to you?",
      "What is your biggest fantasy?",
      "Have you ever gone to the bathroom in the pool?",
      "How many grand-kids do you think you will have?",
      "Who in the group do you think is the wildest in bed?",
      "For guys: have you ever worn lingerie?",
      "Do you have any fetishes?",
      "What is your idea of good s..x?",
      "Do you masturbate?",
      "How many times do you take care of yourself a week?",
      "What is the most s..x that you have had in a day?",
      "What is the longest amount of time that you have gone without intercourse?",
      "What is your favorite position?",
      "Have you ever given oral s..x?",
      "Have you ever received oral s..x?",
      "Have you ever been in a threesome? Would you ever?",
      "How about an orgy?",
      "Would you ever swap partners with anyone?",
      "Have you ever stolen money from your parents?",
      "For girls: what bra size do you wear?",
      "For girls: what is your worst period story?",
      "Do you watch “adult movies”?",
      "Have you ever taken nude photos or videos of yourself?",
      "If you watch x-rated movies what type is your favorite?",
      "Do you have a favorite “adult” store?",
      "Could you live without watching “adult movies”?",
      "Could you live without having s..x for the rest of your life?",
      "Have you ever tried to get out of a speeding ticket?",
      "Who is the craziest person that you know (in person?)",
      "When was a time that you completely lost it?",
      "What kind of pajamas do you wear?",
      "Have you ever stolen something for a store?",
      "Have you ever met a celebrity?",
      "What is an unpopular opinion that you have?",
      "If you weren’t here in this room right now what would you probably be doing?",
      "What kind of person would you want to marry one day?",
      "What do you think happens after we die?",
      "Are you afraid of dying?",
      "What is the best thing that you have ever had to eat?",
      "What is your favorite movie and why?",
      "What is the silliest thing that you have ever done?",
      "What is your favorite thing about the opposite gender (or the gender that you are attracted to?)",
      "Who would play you in a movie about your life?",
      "If you ever wrote a memoir what would the title be?",
      "What is your favorite kind of music to listen to?",
      "Name one thing on your bucket list.",
      "If you could have someone else’s life for one day who would it be?",
      "If you could kiss one celebrity who would it be?",
      "If you could say anything to one person in your life without any consequences what would it be?",
      "If you had to pick one person in your immediate family to survive who would it be?",
      "If you could choose a way to die what would it be?",
      "How many romantic interests do you think you will have for the rest of your life?",
      "Talk about the craziest thing that you overheard.",
      "Was there ever a time in your life that you thought you were going to die?",
      "What was one of the best moments of your life?",
      "What is your best childhood memory?",
      "What is your worst childhood memory?",
      "What kind of parent do you think you will be?",
      "What is the most romantic thing that you have ever done?",
      "What is the most romantic thing that has ever been done for you?",
      "What was your worst workplace experience?",
      "What is the most amount of time that you have ever spent in a hospital?",
      "Where is the furthest place that you have ever traveled to?",
      "Have you ever broken a bone?",
      "Have you ever gotten stitches?",
      "What is the longest amount of time that you have ever been away from home?",
      "What is your most embarrassing puberty-related story?",
      "Where did you used to think babies come from?",
      "How did you find out that Santa Claus is not real?",
      "What is your religion or spirituality?",
      "What is the coolest thing that you have ever done at a job?",
      "What is one thing that you have always wanted to do but have not gotten around to it yet?",
      "Do you have any irrational fears?",
      "What is the sweetest thing that someone could do for you?",
      "Have you ever had a crush on a co-worker?",
      "Have you ever let someone take the blame for something you did? What happened?",
      "Tell us about something really crazy that you were able to get away with.",
    ];

    const randomTruth = truth[Math.floor(Math.random() * truth.length)];
    message.channel.send({
      embeds: [
        new EmbedBuilder()
          .setColor(client.color)
          .setAuthor({
            name: message.author.username,
            iconURL: message.author.displayAvatarURL(),
          })
          .setDescription(`${randomTruth}`),
      ],
    });
  },
};
